### ISSUE TITLE
Cannot compile example

### ISSUE THREAD

**Issue by hang-on** [0x8BitDev/MAPeD-SPReD#1]
Hi, 

I'm trying to compile the "show_sprite" sms example, but I cannot do it. I have wla-dx in the system path.:
----
C:\Users\ANSJ\Documents\GitHub\MAPeD-SPReD\samples\sms\show_sprite>wla-z80 -I ..\common\ -I .\data\ -o ..\bin\show_sprite.o main.asm

WLA Z80 Macro Assembler v9.7b
Written by Ville Helin in 1998-2008 - In GitHub since 2014: https://github.com/vhelin/wla-dx
USAGE: wla-z80 -[iMqtvx]{lo} -I[INCDIR] [DEFINITIONS] <ASM FILE> [OUTPUT FILE]
Commands:             Options:
l  Library file       i  Add list file information
o  Object file        M  Output makefile rules
                      q  Quiet
                      t  Test compile
                      v  Verbose messages
                      x  Extra compile time definitions
                      I  Include directory

linking...

C:\Users\ANSJ\Documents\GitHub\MAPeD-SPReD\samples\sms\show_sprite>wlalink -i -r -v main.link ..\bin\show_sprite.sms

WLALINK GB-Z80/Z80/6502/65C02/6510/65816/HUC6280/SPC-700 WLA Macro Assembler Linker v5.8b
Written by Ville Helin in 2000-2008 - In GitHub since 2014: https://github.com/vhelin/wla-dx
USAGE: wlalink [-bdirsSv] -L[LIBDIR] <LINK FILE> <OUTPUT FILE>
Options:
b  Program file output
d  Discard unreferenced sections
i  Write list files
r  ROM file output (default)
s  Write also a NO$GMB symbol file
S  Write also a WLA symbol file
v  Verbose messages
L  Library directory

Ok!
Could Not Find C:\Users\ANSJ\Documents\GitHub\MAPeD-SPReD\samples\sms\bin\show_sprite.o

C:\Users\ANSJ\Documents\GitHub\MAPeD-SPReD\samples\sms\bin>show_sprite.sms
'show_sprite.sms' is not recognized as an internal or external command,
operable program or batch file.

---

**Comment by 0x8BitDev** [comment]
Hi,

I tried to reproduce the same situation, with your data path and WLA-DX v9.7b ( instead of  **v9.10** I used for the SMS samples; you can read it in the readme file ). And it works well. The sample compiles and runs.

It looks like wla-z80 can't make output file - 'show_sprite.o' in the '..\bin' directory.

So, I don't know... there are several options:

1) May be something is wrong with your rights in the 'Documents' directory. Try to copy 'MAPeD-SPReD\samples\' into any other directory outside of the system 'C:\Users\\' and try there to recompile.

2) May be your security software runs 'compile.bat' in a sandbox. And you need to exclude the 'compile.bat' running from the sandbox. For example, I use the COMODO Security software and it uses sandbox to run unknown programs ( and .bat files too ). And I need to manually ignore running a program in the sandbox.

p.s.: And please use at least WLA-DX **v9.10** to compile all samples successfully. I've found compile errors in other samples with WLA-DX v9.7b.

p.p.s: Just in case, I use Win7 x64 Ultimate

Let me know.

**Comment by hang-on** [comment]
Ah - then it might be something related to my version of WLA. I'm running an older version - but I cannot upgrade at the moment.
